config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    authenticate :user, ->(user) { user.admin? } do
      mount Blazer::Engine, at: 'blazer'
      mount PgHero::Engine, at: 'pghero'
    end
    resources :authorized_hosts, :build_providers, :contacts,
              :devices, :device_builds, :device_properties,
              :device_property_types, :device_property_options, :device_types,
              :events, :groups, :interfaces, :networks, :nodes, :statuses,
              :users, :zones
    root to: 'users#index'
  end

  get 'browse', to: 'visitors#browse'
  root to: 'visitors#index'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  get '/users/confirm/:id', to: 'users#confirm', as: 'confirm_authorization'
  get '/users/revoke/:id', to: 'users#revoke', as: 'revoke_authorization'

  resources :contacts, :device_types, :events, :groups, :networks,
            :statuses, :users
  resources :devices do
    member do
      post 'build'
      get 'build_config'
      get 'conf'
      get 'graph'
    end
  end
  resources :nodes do
    member do
      get 'graph'
    end
  end

  get 'nodes/logos/:id', to: 'nodes#logos'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  get '/android-chrome-192x192.png',
      to: 'visitors#chromeicon_192', format: 'png'
  get '/android-chrome-512x512.png',
      to: 'visitors#chromeicon_512', format: 'png'
  get '/apple-touch-icon.png',
      to: 'visitors#touchicon_180', format: 'png'
  get '/browserconfig.xml',
      to: 'visitors#browserconfig', format: 'xml'
  get '/favicon-16x16.png',
      to: 'visitors#favicon_png16', format: 'png'
  get '/favicon-32x32.png',
      to: 'visitors#favicon_png32', format: 'png'
  get '/favicon.ico',
      to: 'visitors#favicon_ico', format: 'ico'
  get '/mstile-150x150.png',
      to: 'visitors#mstile_150', format: 'png'
  get '/safari-pinned-tab.svg',
      to: 'visitors#maskicon_svg', format: 'svg'
  get '/site.webmanifest',
      to: 'visitors#webmanifest', format: 'json'
end

app/models/node.rb
# frozen_string_literal: true

require_dependency 'dot_diskless'

DIR_URL = 'https://www.google.com/maps?saddr=My+Location&daddr='
TWITTER_BASE = 'https://twitter.com'

# A Node instance represents a physical location at a scale somewhere
# between that of the Zone model and that of the InterfacePoint model.
class Node < ApplicationRecord
  has_paper_trail

  belongs_to :contact, optional: true
  belongs_to :status
  belongs_to :user, optional: true
  belongs_to :group, optional: true
  belongs_to :zone
  has_many :devices
  has_one_attached :logo

  accepts_nested_attributes_for :contact, reject_if: :all_blank

  validates_presence_of :code
  validates_length_of :code, maximum: 64
  validates_uniqueness_of :code, case_sensitive: false
  validates_format_of :code, with: /\A[-_a-zA-Z0-9]+\z/,
                             message: 'contains unacceptable characters',
                             allow_blank: true
  validates_presence_of :name
  validates_uniqueness_of :name
  validates :website, format: URI.regexp(%w[http https]), allow_blank: true
  validates :rss, format: URI.regexp(%w[http https]), allow_blank: true
  validates :twitter, format: /\A[_a-zA-Z0-9]+\z/, allow_blank: true
  validates :wiki, format: URI.regexp(%w[http https]), allow_blank: true
  validates :logo, content_type: { allow: ['image/jpeg', 'image/png'] }

  before_validation :set_defaults

  geocoded_by :address
  after_validation :geocode, if: :should_geocode?
  after_validation :geocode_reset, if: :should_geocode_reset?

  scope :ungrouped, -> { where(group_id: nil) }

  # Reset any existing geocode data.
  def geocode_reset
    self.latitude = nil
    self.longitude = nil
  end

  # Return true if the record should be geocoded.
  def should_geocode?
    address.present? && (address_changed? || !latitude || !longitude)
  end

  # Return true if the geocode data should be reset.
  def should_geocode_reset?
    !address.present?
  end

  # Canonical identifier.
  def to_param
    return unless id

    [id, code].join('-')
  end

  # URL to obtain driving directions.
  def directions_url
    "#{DIR_URL}#{URI.encode_www_form_component(address)}"
  end

  # URL to a Twitter feed.
  def twitter_url
    "#{TWITTER_BASE}/#{twitter}" unless twitter.blank?
  end

  # This method constructs an RGL::AdjacencyGraph instance based on this
  # Node instance, including related Interface instances and IPv4 neighbor
  # relationships.
  def graph(rgl = RGL::AdjacencyGraph.new)
    devices.each { |device| device.graph rgl }
    rgl
  end

  # Set default values.
  def set_defaults
    self.code = name.parameterize if code.blank? && name
    self.uuid ||= SecureRandom.uuid
    self.zone ||= Zone.default
  end

  # Version stamp for the attached logo.
  def logo_stamp
    logo.blob.created_at.to_i if logo.attached?
  end

  # Display-formatted code.
  def display_code
    "Node#{code}"
  end

  # Display-formatted name.
  def display_name
    "#{display_code}: #{name}"
  end
end

app/controllers/admin/nodes_controller.rb
# frozen_string_literal: true

module Admin
  class NodesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/node_controller.rb
#--
# $Id: node_controller.rb 2746 2006-06-11 01:36:32Z keegan $
# Copyright 2004-2006 Keegan Quinn
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#++

class NodeController < ApplicationController
  include ActionView::Helpers::TagHelper

  before_filter :login_required, :except => [
    :comment_feed, :log_feed, :graph, :show, :wl
  ]

  def index
    redirect_to :controller => 'welcome'
  end

  def show
    @node = Node.find_by_code(params[:code])

    unless logged_in? or @node.expose?
      redirect_to(:controller => 'welcome') and return
    end

    @page_heading = 'Node: ' + @node.name
    @head_content = [
      tag(:link, {
            :rel => 'alternate',
            :type => 'application/atom+xml',
            :title => 'Node log feed (Atom)',
            :href => url_for(:action => 'log_feed', :code => @node.code)
          }),
      tag(:link, {
            :rel => 'alternate',
            :type => 'application/atom+xml',
            :title => 'Node comment feed (Atom)',
            :href => url_for(:action => 'comment_feed', :code => @node.code)
          })
    ].join("\n")

    markers = []
    @node.hosts.each do |host|
      if point = host.average_point
        markers << GMarker.new([point[:latitude], point[:longitude]],
                               :title => host.name,
                               :info_window => "<a href=\"" +
                                   url_for(:controller => 'host',
                                           :action => 'show',
                                           :node_code => @node.code,
                                           :hostname => host.name) +
                                   "\">" + host.name + "</a>")
      end
    end

    unless markers.empty?
      @map = GMap.new('node_map')
      @map.overlay_init Clusterer.new(markers)
      @map.center_zoom_init markers.first.point, 15
    end
  end

  def new
    @node = Node.new(params[:node])
    @node.zone = Zone.find_by_code params[:zone_code]
    @node.user = current_user

    @page_heading = 'New node'

    unless request.post?
      @node.country = AH_DEFAULT_COUNTRY
      @node.state = AH_DEFAULT_STATE
      @node.city = AH_DEFAULT_CITY
      return
    end

    if @node.save
      flash[:notice] = 'Node was successfully created.'

      redirect_to(:controller => 'zone',
                  :action => 'show',
                  :code => @node.zone.code)
    end
  end

  def edit
    @node = Node.find_by_code(params[:code])

    @page_heading = 'Node: ' + @node.name

    return unless request.post?

    if @node.update_attributes(params[:node])
      flash[:notice] = 'Node was successfully updated.'
      redirect_to :action => 'show', :code => @node.code
    end
  end

  def destroy
    node = Node.find_by_code(params[:code])
    zone = node.zone
    node.destroy

    flash[:notice] = 'Node was successfully destroyed.'

    redirect_to(:controller => 'zone',
                :action => 'show',
                :code => zone.code)
  end

  def graph
    node = Node.find_by_code(params[:code])

    unless logged_in? or node.expose?
      redirect_to(:controller => 'welcome') and return
    end

    send_data(node.graph.to_png,
              :type => 'image/png', :disposition => 'inline')
  end

  def comment_feed
    @node = Node.find_by_code(params[:code])

    unless logged_in? or @node.expose?
      redirect_to(:controller => 'welcome') and return
    end

    render :layout => false
  end

  def log_feed
    @node = Node.find_by_code(params[:code])

    unless logged_in? or @node.expose?
      redirect_to(:controller => 'welcome') and return
    end

    render :layout => false
  end

  def wl
    @node = Node.find_by_code(params[:code])

    unless logged_in? or @node.expose?
      redirect_to(:controller => 'welcome') and return
    end

    render :layout => false
  end
end

app/controllers/nodes_controller.rb
# frozen_string_literal: true

# This controller facilitates interaction with Nodes.
class NodesController < ApplicationController
  before_action :authenticate_user!, except: %i[show graph]
  after_action :verify_authorized

  # Show action.
  def show
    @node = authorize Node.find(params[:id])
    serve_image if params[:format] == 'png'
  rescue ActiveRecord::RecordNotFound
    @node = authorize Node.find_by_code(params[:id])
    raise unless @node

    redirect_to node_path(@node)
  end

  # New action.
  def new
    @node = authorize Node.new(user_id: current_user.id)
  end

  # Create action.
  def create
    @node = authorize Node.new(permitted_attributes(Node))
    save_and_respond @node, :created, :create_success
  end

  # Edit action.
  def edit
    @node = authorize Node.find(params[:id])
  end

  # Update action.
  def update
    @node = authorize Node.find(params[:id])
    @node.assign_attributes permitted_attributes(@node)
    save_and_respond @node, :ok, :update_success
  end

  # Destroy action.
  def destroy
    @node = authorize Node.find(params[:id])
    destroy_and_respond @node, browse_path
  end

  # Graph action.
  def graph
    @node = authorize Node.find(params[:id])

    respond_to do |format|
      format.png do
        send_data @node.graph.to_png, type: 'image/png', disposition: 'inline'
      end
      format.any { redirect_to format: :png }
    end
  end

  private

  def blob
    @node.logo.blob
  end

  def serve_image
    return head(:not_found) unless @node.logo.attached?

    expires_in 1.year, public: true
    send_data blob.service.download(blob.key),
              type: blob.content_type, disposition: 'inline'
  end
end

app/views/nodes/_contact_fields.html.haml
.contact-fields.nested-fields.border.border-dark.rounded.mb-2.p-2
  = render partial: 'contacts/form', locals: { contact: f.object, f: f }

  .clearfix
    .float-right
      &middot;
      = link_to_remove_association f do
        = t(:remove_h, thing: Contact.model_name.human)

app/views/nodes/_form.html.haml
%p
  Unless otherwise specified, any details you provide here will be
  available to the public. Please be sure not to include any information
  you wish to remain private.

= f.input :code
.mb-3.text-muted
  A unique identifier for this node. We suggest using the node's WikiWord
  without the prefix. For example, NodePioneerSquare would have the code
  PioneerSquare. If your node doesn't have a WikiWord yet, you can make one up.

= f.input :name
.mb-3.text-muted Proper name of the area or business where the node is located.

.row
  .col-6
    = f.association :status
  .col-6
    = f.association :group

- if current_user.admin?
  = f.association :user

= f.input :body
.mb-3.text-muted Description of the node. Any relevant information can go here.

= f.input :address
.mb-3.text-muted
  Street address of the node. This will be used to determine the position of
  the map marker.
= f.input :hours

= f.input :notes
.mb-3.text-muted
  Notes about the node. Technical or miscellaneous information can go here.

= year_select f, :live_date

= f.input :website
= f.input :rss

= f.input :twitter
.mb-3.text-muted Twitter username. Do not include @ symbol.

= f.input :wiki

= f.input :logo
.mb-3.text-muted
  Square images in PNG format work best.

%h3 Contact

#contact
  - if @node.contact.present? && !@node.contact.persisted?
    = f.simple_fields_for :contact do |contact|
      = render 'contact_fields', f: contact
  - unless current_user.contacts.empty?
    #contact-select
      = f.association :contact, label: false
  .links.mb-3
    &middot;
    = link_to_add_association f, :contact do
      = t(:add_new_h, thing: Contact.model_name.human)

= hidden_field_tag :authenticity_token, form_authenticity_token

app/views/nodes/_marker.html.haml
= link_to node.name, url_for(node)

%p.small
  %span{style: "color: #{node.status.color}"}
    = t :status, status: node.status.name

- if node.address
  %p= node.address
  %p= link_to t(:get_directions), "https://www.google.com/maps?saddr=My+Location&daddr=#{URI.encode(node.address)}", target: :_blank

- if node.hours?
  %p= t :hours, hours: node.hours

app/views/nodes/_node.html.haml
= link_to node.name, url_for(node)

%p.small
  %span{ class: node.status.color }
    = t :status, status: node.status.name

- if node.address
  %p= node.address
  %p= link_to t(:get_directions), node.directions_url, target: :_blank

- if node.hours?
  %p= t :hours, hours: node.hours

app/views/nodes/edit.html.haml
- content_for :meta_title, t(:edit_h, thing: Node.model_name.human)

%h1= t :edit_h, thing: Node.model_name.human

= simple_form_for @node, turbolinks_form: true, validate: true do |f|
  = render partial: 'form', locals: { f: f }

  = f.submit t(:update), class: 'btn btn-primary'
  = link_to t(:cancel), url_for(@node), class: 'btn btn-warning'

app/views/nodes/new.html.haml
- content_for :meta_title, t(:new_h, thing: Node.model_name.human)

%h1= t :new_h, thing: Node.model_name.human

%p
  Here you can create a new node. Nodes registered in this system will be
  included in our database and displayed on the map.

= simple_form_for @node, turbolinks_form: true, validate: true do |f|
  = render partial: 'form', locals: { f: f }

  = f.input :user_id, as: :hidden
  = f.submit t(:create), class: 'btn btn-primary'
  = link_to t(:cancel), browse_path, class: 'btn btn-warning'

app/views/nodes/show.html.haml
- content_for :meta_title, @node.display_name

%h2= h @node.name

- unless @node.status.blank?
  %p
    = status_color @node.status do
      = t :status, status: @node.status.name

= markdown @node.body

.row
  .col-lg-8.pb-3
    - if @node.address?
      %p= @node.address

    - if @node.hours?
      %p= t :hours, hours: @node.hours

    - if @node.latitude && @node.longitude
      = map_tag @node
      .text-muted.text-right
        = link_to t(:get_directions), @node.directions_url, target: :_blank

    - if @node.notes?
      = markdown @node.notes

    %ul.list-group.list-group-horizontal
      - unless @node.website.blank?
        %li.list-group-item
          = link_to 'Website', @node.website, target: :_blank

      - unless @node.rss.blank?
        %li.list-group-item
          = link_to 'RSS Feed', @node.rss, target: :_blank

      - unless @node.twitter.blank?
        %li.list-group-item
          = link_to 'Twitter', @node.twitter_url, target: :_blank

      - unless @node.wiki.blank?
        %li.list-group-item
          = link_to 'Wiki', @node.wiki, target: :_blank

    - if policy(@node).update? || @node.devices.count.positive?
      %h3.mt-3= Device.model_name.human(count: 2)

      %ul
        - @node.devices.each do |device|
          %li
            = link_to device.name, url_for(device)
            - unless device.device_type.blank?
              &mdash;
              = device.device_type.name
            - unless device.interfaces.empty?
              (#{device.interfaces.count} interfaces)
        - if policy(@node).update?
          %li
            = link_to t(:new_device), new_device_path(node: @node)

    - if @node.graph&.edges&.count&.positive?
      %h3.mt-3= t('.network_diagram')
      %p= image_tag graph_node_path(@node, format: :png)

  .col-lg-4
    - if @node.logo.attached?
      %p= image_tag node_path(@node, format: 'png', _v: @node.logo_stamp)

    = render partial: 'shared/edit_delete', locals: { record: @node }

    %p.small
      = t :code, code: @node.display_code
      %br/
      - unless @node.group.blank?
        Managed By:
        = link_to @node.group.name, url_for(@node.group)
        %br/
      - if @node.group.blank? && @node.user&.visible?
        Owner:
        = link_to @node.user.name, url_for(@node.user)
        %br/
      - unless @node.live_date.blank?
        #{t :live_date}: #{@node.live_date.to_s(:db)}
        %br/
      = t :created, date: @node.created_at.localtime.to_s
      %br/
      = t :updated, date: @node.updated_at.localtime.to_s