config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    authenticate :user, ->(user) { user.admin? } do
      mount Blazer::Engine, at: 'blazer'
      mount PgHero::Engine, at: 'pghero'
    end
    resources :authorized_hosts, :build_providers, :contacts,
              :devices, :device_builds, :device_properties,
              :device_property_types, :device_property_options, :device_types,
              :events, :groups, :interfaces, :networks, :nodes, :statuses,
              :users, :zones
    root to: 'users#index'
  end

  get 'browse', to: 'visitors#browse'
  root to: 'visitors#index'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  get '/users/confirm/:id', to: 'users#confirm', as: 'confirm_authorization'
  get '/users/revoke/:id', to: 'users#revoke', as: 'revoke_authorization'

  resources :contacts, :device_types, :events, :groups, :networks,
            :statuses, :users
  resources :devices do
    member do
      post 'build'
      get 'build_config'
      get 'conf'
      get 'graph'
    end
  end
  resources :nodes do
    member do
      get 'graph'
    end
  end

  get 'nodes/logos/:id', to: 'nodes#logos'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  get '/android-chrome-192x192.png',
      to: 'visitors#chromeicon_192', format: 'png'
  get '/android-chrome-512x512.png',
      to: 'visitors#chromeicon_512', format: 'png'
  get '/apple-touch-icon.png',
      to: 'visitors#touchicon_180', format: 'png'
  get '/browserconfig.xml',
      to: 'visitors#browserconfig', format: 'xml'
  get '/favicon-16x16.png',
      to: 'visitors#favicon_png16', format: 'png'
  get '/favicon-32x32.png',
      to: 'visitors#favicon_png32', format: 'png'
  get '/favicon.ico',
      to: 'visitors#favicon_ico', format: 'ico'
  get '/mstile-150x150.png',
      to: 'visitors#mstile_150', format: 'png'
  get '/safari-pinned-tab.svg',
      to: 'visitors#maskicon_svg', format: 'svg'
  get '/site.webmanifest',
      to: 'visitors#webmanifest', format: 'json'
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true

# Visitors controller. This controller serves the default root page and all
# of the theme-related assets from the default Zone.
class VisitorsController < ApplicationController
  layout 'big', only: [:index]
  before_action :set_zone

  # Index action.
  def index
    serve_image :nav_logo if params[:format] == 'png'
  end

  # Serve the current Android/Chrome 192x192 icon.
  def chromeicon_192
    serve_image :chromeicon_192
  end

  # Serve the current Android/Chrome 512x512 icon.
  def chromeicon_512
    serve_image :chromeicon_512
  end

  # Serve the current Apple touch icon.
  def touchicon_180
    serve_image :touchicon_180
  end

  # Serve the current 16x16 PNG icon.
  def favicon_png16
    serve_image :favicon_png16
  end

  # Serve the current 32x32 PNG icon.
  def favicon_png32
    serve_image :favicon_png32
  end

  # Serve the current favorites icon.
  def favicon_ico
    serve_image :favicon_ico
  end

  # Serve the current Microsoft 150x150 tile icon.
  def mstile_150
    serve_image :mstile_150
  end

  # Serve the current mask SVG.
  def maskicon_svg
    serve_image :maskicon_svg
  end

  private

  def set_zone
    @zone = Zone.default
  end

  def blob(attr)
    if params[:resize]
      attr.variant(resize: params[:resize], quality: '00').processed
    else
      attr.blob
    end
  end

  def serve_image(key)
    attr = Zone.default.send(key)
    return head(:not_found) unless attr&.attached?

    expires_in 1.year, public: true
    send_data blob(attr).service.download(blob(attr).key),
              type: attr.blob.content_type, disposition: 'inline'
  end
end

app/views/visitors/_my_things.html.haml
%h2= t '.my_nodes'

.small.text-muted.pb-1
  = link_to 'Create Node', new_node_path
  = surround '(', ')' do
    = t :owned_numbered, count: current_user.nodes.ungrouped.count

- unless current_user.nodes.ungrouped.empty?
  %ul
    - current_user.nodes.ungrouped.order(name: :asc).each do |node|
      %li= link_to h(node.name), url_for(node)

%h2= t '.my_devices'

.small.text-muted.pb-1
  = link_to 'Create Device', new_device_path
  (#{t(:owned_numbered, count: current_user.devices.ungrouped.count)})

- unless current_user.devices.ungrouped.empty?
  %ul
    - current_user.devices.ungrouped.order(name: :asc).each do |device|
      %li= link_to h(device.name), url_for(device)

%h2= t '.my_contacts'

.small.text-muted.pb-1
  = link_to 'Create Contact', new_contact_path
  = surround '(', ')' do
    = t :owned_numbered, count: current_user.contacts.ungrouped.count

- unless current_user.contacts.ungrouped.empty?
  %ul
    - current_user.contacts.ungrouped.order(name: :asc).each do |contact|
      %li= link_to h(contact.name), url_for(contact)

app/views/visitors/browse.html.haml
- content_for :meta_title, t(:browse)

= markdown Zone.default&.body

.row
  .col-lg-8.pb-3
    - if Zone.default && !Zone.default.nodes.empty?
      %h2= Node.model_name.human.pluralize

      .small.text-muted.pb-1
        = surround '(', ')' do
          = t :total_numbered, count: Zone.default.nodes.count

      %table{ data: { 'sort-name': 'code' }.merge(searchable_table) }
        %thead
          %tr
            %th{ data: { field: 'code' }.merge(sortable_row) } Code
            %th{ data: { field: 'name' }.merge(sortable_row) } Name
        %tbody
          - Zone.default.nodes.order(code: :asc).each do |node|
            %tr
              %td= link_to h(node.display_code), url_for(node)
              %td= link_to h(node.name), url_for(node)

  .col-lg-4
    - unless user_signed_in?
      %h2= t :join_us

      %ul
        %li= link_to t(:sign_in), user_session_path
        %li= link_to t(:sign_up), new_user_registration_path

    - if user_signed_in?
      = render partial: 'my_things'

    - unless Group.all.empty?
      %h2= Group.model_name.human.pluralize

      .small.text-muted.pb-1
        = surround '(', ')' do
          = t :total_numbered, count: Group.count

      %ul
        - Group.all.order(name: :asc).each do |group|
          %li
            = link_to h(group.name), url_for(group)

    - unless User.visible.empty?
      %h2= User.model_name.human.pluralize

      .small.text-muted.pb-1
        = surround '(', ')' do
          = succeed(',') do
            = t :total_numbered, count: User.count
          = t :visible_numbered, count: User.visible.count

      %ul
        - User.visible.order(name: :asc).each do |user|
          %li
            = link_to h(user.name), url_for(user)

    - unless DeviceType.all.empty?
      %h2= DeviceType.model_name.human.pluralize

      .small.text-muted.pb-1
        = surround '(', ')' do
          = t :total_numbered, count: DeviceType.count

      %ul
        - DeviceType.all.order(:name).each do |device_type|
          %li
            = link_to h(device_type.name), url_for(device_type)

    - unless Network.all.empty?
      %h2= Network.model_name.human.pluralize

      .small.text-muted.pb-1
        = surround '(', ')' do
          = t :total_numbered, count: Network.count

      %ul
        - Network.all.order(name: :asc).each do |network|
          %li
            = link_to h(network.name), url_for(network)

    - unless Status.all.empty?
      %h2= Status.model_name.human.pluralize

      .small.text-muted.pb-1
        = surround '(', ')' do
          = t :total_numbered, count: Status.count

      %ul
        - Status.all.order(name: :asc).each do |status|
          %li
            = link_to h(status.name), url_for(status)

app/views/visitors/index.html.haml
= map_tag